name: Generate contribution snake
on:
  schedule:
    - cron: "23 2 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-tucapp.svg?palette=github-dark&color_snake=%23FF6B35&color_dots=%2316120C,%23392F22,%23B99671,%23F7EEDD,%23FFD23F
      - name: Publish animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
